### ISSUE TITLE
Revise the Autonomous Route Document

### ISSUE THREAD

**Issue by SourishMurthy1** [NRG948/NRGRobot2018#18]
Just go through every route make sure the description is accurate, if not change the description accordingly

**Comment by ghost** [comment]
@nelsonfang117 and i are redoing the entire autonomous route, je n'aime pas. ): Pictures and values were inaccurate, so we are finding the most effective way and making accurate diagrams.

**Comment by chandrap2** [comment]
@mwgreatest do you have a slack account; I don't see you on it... if not, you need to get one, since most team/subgroup announcements are posted there. Thanks.

**Comment by Acchindra** [comment]
[Revised Auto Routines.pdf](https://github.com/NRG948/NRGRobot2018/files/1680368/Revised.Auto.Routines.pdf)

**Comment by acchindra-thev** [comment]
[Auto Routines.pdf](https://github.com/NRG948/NRGRobot2018/files/1680398/Auto.Routines.pdf)

Idea for efficient auto routines.

**Comment by SourishMurthy1** [comment]
Done by Me, Chuwei and Valliappan
