### ISSUE TITLE
Issue #2 Research Autonomous movement with Mecanum Wheels.

### ISSUE THREAD

**Issue by ChuweyBar** [NRG948/NRGRobot2018#2]
As we all know (or should know), we are using Mecanum wheels this year.
Which means extra work during Autonomous. 
While using tank drive, motor controllers give us the exact rotation of the motor, thus with some calibration, we know how far we are traveling.
However, mecanum wheel slips while spinning and they can also go sideways. (If you have a question regarding strafing and mecanum wheel slipping, do some research or ask leadership when they are not busy)
Go on ChiefDelphi or any search engine and research how are we going to calculate the exact distance we are moving/strafing. 
Results are expected within a week. The faster the better.

**Comment by edreed** [comment]
Although there may be other threads, the one on Chief Delphi on [Mecanum Encoder Algorithm](https://ftcforum.usfirst.org/forum/ftc-technology/50373-mecanum-encoder-algorithm) is relevant and includes references to FRC Team 492 - Titan Robotics [source](https://github.com/trc492/FtcSamples/blob/master/Ftc3543Lib/src/main/java/trclib/TrcDriveBase.java) for calculating distance. The algorithm is buried in the `public void preContinuousTask(TrcRobot.RunMode runMode)` method.

**Comment by concodeia** [comment]
For navigating around the field (in autonomous), we could use an ultrasonic and/or color sensor along with encoders.

**Comment by chemwiz** [comment]
if we know the number of rotation then we can use a formula to find the distance travelled as even while strafing we are spinning the wheel

**Comment by Jeffreyxu11** [comment]
It should be, in theory, the same as moving straight, because even when we are strafing, the wheels are moving forwards or backwards. so if we calculate the distance for one rotation of all of the wheels, we can measure how far they would move/rotation.

**Comment by ChuweyBar** [comment]
According to @edreed 's previous comment, we can use Tomas to test out Titan Robotics' code. @SourishMurthy1 can you bring some rookies to work on that?
