### ISSUE TITLE
Issue #3 Research Vision Tracking

### ISSUE THREAD

**Issue by ChuweyBar** [NRG948/NRGRobot2018#3]
This year we are switching from the Microsoft Webcam to PixyCam. 
While the Webcam is supported by FIRST Libraries, PixyCam is not.
There are many related discussions of PixyCam on ChiefDelphi.
There are also a lot of teams who are already using PixyCam, thus digging into their code for some "Reference" is also an option.
Some research was done by Valliappan and Nipun on 492 Titan Robotics' PixyCam code:
https://docs.google.com/document/d/1AePsrbJKPeVE3NWi5QkJotGPT_W3hm1bSUtkd3oFb1o/edit?usp=sharing
So we already have a head start.
The main goal of this research is to figure out how to talk to PixyCam, teach it objects (ask Mr.Fagan), and get the output from PixyCam. Outputs include but are not limited to: Length and Height of the Target object, X, Y coordinate, etc.
Results are expected in a week. (Sooner is better)

**Comment by Jeffreyxu11** [comment]
http://www.cmucam.org/projects/cmucam5/wiki/Teach_Pixy_an_object_2 I found this link on how to teach pixycam an object. There is also a video on the link to teach how to do it.
