### ISSUE TITLE
Issue #4 FRC Simulator

### ISSUE THREAD

**Issue by ChuweyBar** [NRG948/NRGRobot2018#4]
There's a simulator for FRC code online!
Investigate!
The following website is for the FRCSim. 
http://first.wpi.edu/FRC/roborio/release/simulation/
We need to know how can we use it, is there any restrictions, is it a plug and play etc.
The more we know the better. Since sometimes we will need to test code without a robot. 
I expect some documentation of instructions to use FRCSim within around a week.

**Comment by ChuweyBar** [comment]
Looks like the FRC Simulator Sourish was using only support up to 2016 code.

**Comment by SourishMurthy1** [comment]
The FRC sim is discontinued after 2016
