### ISSUE TITLE
Issue #5 Installing Plugins and NI Update Suite

### ISSUE THREAD

**Issue by ChuweyBar** [NRG948/NRGRobot2018#5]
As we stepping into the building season, personal computer is now allowed and does provide many conveniences, for we need to install a lot of .exe files that school laptop freaks out about.

So, if you have a personal computer, start doing these at home. (BSD network ain't too happy about things we are downloading)

1. Install Eclipse and Github. 
2. Install Eclipse plugins. 
    https://wpilib.screenstepslive.com/s/currentCS/m/getting_started/l/599679-installing-eclipse-c-java
    Follow the steps from "Configuring Eclipse"
3. Installing the NI Update Suite (Optional, you get driver station and radio config)
    https://wpilib.screenstepslive.com/s/currentCS/m/getting_started/l/599670-installing-the-frc-update-suite-all-languages

**Comment by dowhep** [comment]
No personal laptop... :(

**Comment by edreed** [comment]
@ChuweyBar It would be good to move this information to the READMD.md file so that all see it when they come to the repository.

**Comment by ChuweyBar** [comment]
All information moved to Readme. Closing issue.
